name: tastemaker
favicon: null
layout_spectrum: 0.8924798413645476
typography_spectrum: 0.3021657792851329
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.09190977388061583
  lightness: 0.10661112633533776
  saturation: 0.985428603598848
  rhythmicContrast: 0.2935744144488126
purpose: []
