name: tastemaker
favicon: null
layout_spectrum: 0.8924798413645476
typography_spectrum: 0.3021657792851329
title: tastemaker
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75212127-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a01c96'
    - '#b957ac'
    - '#d7a9ce'
    - '#18161e'
  brandStrength: 0.125
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
